#!/bin/bash
#Decrypted By YADDY D PHREAKER
#!/bin/bash
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

clear
echo " "
echo " "

if [ -e "/var/log/auth.log" ]; then
        LOG="/var/log/auth.log";
fi
if [ -e "/var/log/secure" ]; then
        LOG="/var/log/secure";
fi
echo -n >  /tmp/id
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "              SSH USER LOGIN            $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "   User"     "       Last Login"      " Total IP"
echo -e "\033[1;91m┌──────────────────────────────────────────┐\033[0m"
cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/login-db.txt
data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

for PID in "${data[@]}"
do
            cat /tmp/login-db.txt | grep "sshd\[$PID\]" > /tmp/login-db-pid.txt;
            NUM=`cat /tmp/login-db-pid.txt | wc -l`;
            USER=`cat /tmp/login-db-pid.txt | awk '{print $9}'`;
            IP=`cat /tmp/login-db-pid.txt  | awk '{print $11}'`;
            if [ $NUM -eq 1 ]; then
            echo "### $PID" "$USER" "$IP" >> /tmp/id
#                    printf "  %-13s %-7s %-8s %2s\n"  "$PID - $USER - $IP";
        fi
done
ceks=$(cat /tmp/id)
if [[ ${ceks} != "" ]]; then
data=$(cat  /tmp/id | grep '###' | cut -d ' ' -f 3)
for user in ${data[@]}; do
  nyet=$(cat /tmp/id | grep "${user}" | cut -d ' ' -f 3 | wc -l)
   coks=$(cat /tmp/id | wc -l)
   lastlogin=$(cat $LOG | grep -w "$user" | tail -n 500 | cut -d " " -f 2 | tail -1)
   if [[ ${coks} -gt 0 ]]; then
   printf "  %-13s %-7s %-8s %2s\n"  "$user" "$lastlogin" "$nyet"
fi
done
fi
echo ""
echo -e "\033[1;91m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "        Autoscript Mod by MyridWan        "
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"

m-ssh
